// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteRecord'](arg1, arg2);
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewRecord(arg1, arg2) {
  return window['go']['main']['App']['NewRecord'](arg1, arg2);
}

export function SaveRecord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRecord'](arg1, arg2, arg3);
}

export function ValidateExpr(arg1) {
  return window['go']['main']['App']['ValidateExpr'](arg1);
}
