// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCancel(arg1) {
  return window['go']['main']['App']['AddCancel'](arg1);
}

export function AddRedirect(arg1) {
  return window['go']['main']['App']['AddRedirect'](arg1);
}

export function GenerateCert() {
  return window['go']['main']['App']['GenerateCert']();
}

export function GetCancels() {
  return window['go']['main']['App']['GetCancels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRedirects() {
  return window['go']['main']['App']['GetRedirects']();
}

export function RemoveCancel(arg1) {
  return window['go']['main']['App']['RemoveCancel'](arg1);
}

export function RemoveRedirect(arg1) {
  return window['go']['main']['App']['RemoveRedirect'](arg1);
}

export function SaveCancel(arg1, arg2) {
  return window['go']['main']['App']['SaveCancel'](arg1, arg2);
}

export function SaveRedirect(arg1, arg2) {
  return window['go']['main']['App']['SaveRedirect'](arg1, arg2);
}

export function StartProxy(arg1) {
  return window['go']['main']['App']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
