// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxyPort(arg1) {
  return window['go']['main']['App']['AddProxyPort'](arg1);
}

export function AddRule(arg1) {
  return window['go']['main']['App']['AddRule'](arg1);
}

export function AddWebPort(arg1) {
  return window['go']['main']['App']['AddWebPort'](arg1);
}

export function GenerateCert() {
  return window['go']['main']['App']['GenerateCert']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetManyRules(arg1) {
  return window['go']['main']['App']['GetManyRules'](arg1);
}

export function GetOneRequest(arg1) {
  return window['go']['main']['App']['GetOneRequest'](arg1);
}

export function GetOneRule(arg1) {
  return window['go']['main']['App']['GetOneRule'](arg1);
}

export function GetOutboundIP() {
  return window['go']['main']['App']['GetOutboundIP']();
}

export function IsProxyRunning() {
  return window['go']['main']['App']['IsProxyRunning']();
}

export function IsWebServerRunning() {
  return window['go']['main']['App']['IsWebServerRunning']();
}

export function RemoveRule(arg1) {
  return window['go']['main']['App']['RemoveRule'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StartWebServer() {
  return window['go']['main']['App']['StartWebServer']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}

export function UpdateRule(arg1) {
  return window['go']['main']['App']['UpdateRule'](arg1);
}
