// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRedirect(arg1:main.Redirect):Promise<void>;

export function GetRedirects():Promise<main.ReturnValue>;

export function RemoveRedirect(arg1:number):Promise<void>;

export function SaveRedirect(arg1:number,arg2:main.Redirect):Promise<void>;
