// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddConfigPort(arg1:string):Promise<void>;

export function AddRule(arg1:main.InValue):Promise<main.ReturnValue>;

export function GenerateCert():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetLogs():Promise<main.ReturnValue>;

export function GetManyRules(arg1:string):Promise<main.ReturnValue>;

export function GetOneRule(arg1:number):Promise<main.ReturnValue>;

export function RemoveRule(arg1:number):Promise<main.ReturnValue>;

export function StartProxy():Promise<main.ReturnValue>;

export function StartWebServer():Promise<main.ReturnValue>;

export function StopProxy():Promise<void>;

export function UpdateRule(arg1:main.InValue):Promise<main.ReturnValue>;
